services:
  app:
    container_name: app
    image: md-maker:0.0.1
    build:
      context: .
      target: dev
    ports:
      - "8080:5173"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      NODE_ENV: development
    command: /bin/bash
    tty: true
volumes:
  node_modules:
